### PR TITLE
fix: remove example app tests

### PR DESCRIPTION
**Pull request by smyrick**
Remove the tests folder from the example app as this is causing coverage reports to drop in codecov

Screen Shot 2019-08-02 at 5 07 11 PM

### CODE REVIEW

**Comment by smyrick** [comment]
☝️ Back up to `96.85%`

**Comment by dkuc84** [comment]
Instead of removing tests from example app. I'd rather add some integration tests that ensure that we can start the app, generate the schema, execute some queries and verify their responses.

**Comment by smyrick** [comment]
@dkuc84 I'm fine with that but I don't think the sample app needs to be included in the code coverage report. So maybe we can instead change the codecov config

**Comment by smyrick** [comment]
Closing in favor of https://github.com/ExpediaDotCom/graphql-kotlin/pull/297

**Pull request closed without merging**
